name: Dotnet Publish Oak.TaskScheduler Package

on: 
  workflow_dispatch:
  workflow_run:
    workflows: ["Dotnet Publish Packages"]
    types:
      - completed

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore src/Oak.TaskScheduler/

    - name: Build
      run: dotnet build src/Oak.TaskScheduler/ --no-restore --configuration=Release

    - name: Test
      run: dotnet test tests/

    - name: Pack
      run: dotnet pack src/Oak.TaskScheduler/ --configuration=Release

    - name: Authenticate
      run: dotnet nuget add source --username ChrisWeaver1 --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/weavc/index.json"

    - name: Publish
      run: dotnet nuget push src/Oak.TaskScheduler/bin/Release/*.nupkg --source "github"
