name: Dotnet Publish Oak.TaskScheduler Package

on: []

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore Oak.TaskScheduler/

    - name: Build
      run: dotnet build Oak.TaskScheduler/ --no-restore --configuration=Release

    - name: Test
      run: dotnet test tests/ --verbosity normal

    - name: Pack
      run: dotnet pack Oak.TaskScheduler --configuration=Release

    - name: Authenticate
      run: otnet nuget add source --username ChrisWeaver1 --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/weavc/index.json"

    - name: Publish
      run: dotnet nuget push Oak.TaskScheduler/bin/Release/*.nupkg --source "github"
